name: CI Build

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest]
        target: [esp32, esp32s2, esp32s3, esp32c3, esp32h2, esp32p4]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
      - uses: espressif/esp-idf-ci-action@v1
        with:
          esp_idf_version: v5.2
          target: ${{ matrix.target }}
      - name: Copy diagram ${{ matrix.target }}
        run: |
          cp .github/workflows/wokwi/diagram-${{ matrix.target }}.json diagram.json
      - uses: wokwi/wokwi-ci-action@v1
        with:
          token: ${{ secrets.WOKWI_CI_TOKEN }}
          timeout: 50000
          expect_text: 'Hello, world from Zig!'
